# .github/workflows/deploy.yml
name: Deploy Personal Next.js Website to Vercel

on:
  push:
    branches:
      - main  # auto deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies and build
      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      # 4. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: .
