# .github/workflows/deploy.yml
name: Deploy Personal Next.js Website to Vercel

on:
  push:
    branches:
      - main  # deploy on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run lint & tests (optional)
      - name: Run lint
        run: npm run lint || true

      - name: Run tests
        run: npm test || true

      # 5. Build the project
      - name: Build Next.js
        run: npm run build

      # 6. Deploy to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v21
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_USER_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          vercel-args: "--prod"  # deploy to production
          